### ISSUE TITLE
<ul>'s within content are indented

### ISSUE THREAD

**Issue by dashouse** [alphagov/product-page-example#31]
When adding a list it appears indented. Not aligned with http://govuk-elements.herokuapp.com/typography/#typography-lists

<img width="652" alt="screen shot 2017-01-19 at 11 41 05" src="https://cloud.githubusercontent.com/assets/23356842/22105487/30776676-de3c-11e6-839c-6c1b9884fc4c.png">

**Comment by 36degrees** [comment]
Pretty sure this will be fixed by #18 which includes the list styles from elements.

**Comment by 36degrees** [comment]
Fixed by #18
