### ISSUE TITLE
Buttons don't use nta font-family

### ISSUE THREAD

**Issue by olly** [alphagov/product-page-example#43]
The buttons on [GOV.UK Elements](https://govuk-elements.herokuapp.com/buttons/) use the "nta" font family, but buttons in the product page don't.

As far as I can tell this is because [`_core.scss`](https://github.com/alphagov/product-page-example/blob/760697c33882d6beb10f3a8a14a609a7ade9050a/source/stylesheets/_core.scss) doesn't include the `input` rule defined in [govuk_template's `_basic.scss`](https://github.com/alphagov/govuk_template/blob/e9ae7ff045e0adf552aeed509be5ef174be325aa/source/assets/stylesheets/_basic.scss#L6).

Credit to eagle-eyed @christopherthomasdesign for noticing the difference!

**Comment by 36degrees** [comment]
Closed by #50
