### ISSUE TITLE
Reliance on (retired) GOV.UK Frontend Toolkit 

### ISSUE THREAD

**Issue by kjdchapman** [alphagov/product-page-example#48]
Given [GOV.UK Design System](https://github.com/alphagov/govuk-design-system) is the newer, maintained product, it would be best if this template was built on top of it, not the [Frontend Toolkit](https://github.com/alphagov/govuk_frontend_toolkit).

It looks like this repo isn't under active maintenance, but I thought it worth noting - maybe something in the README would warn future users?

Notably, this repo has been a huge boon for us, and helped us get up and running quickly - I'm grateful for its existence, but would like make future users aware of this issue.

**Comment by nickcolley** [comment]
I'm interested in picking this up if I have time in the firebreak (time between missions)

**Comment by jonheslop** [comment]
I’ve transitioned GOV.UK Pay’s product page over to the design system. I need to port the changes over here. It wouldn’t take me long, will get on it ASAP

**Comment by jonheslop** [comment]
Will be solved by — https://github.com/alphagov/product-page-example/issues/49

**Comment by kjdchapman** [comment]
Oh, nice! I'm happy to help out - though that's probably just by being a brief second pair of eyes given my current workload / level of familiarity with the tools involved.

**Comment by 36degrees** [comment]
Closed by #50
